atoptima/Coluna.jl

src/constraints.jl
src/nodealgs/algevalnode.jl
src/nodealgs/alggeneratechildrennodes.jl
src/problem.jl
src/varconstr.jl
src/variables.jl

I will add some comments below to answer some questions in the comments

Applying fixes using suggestions from FV

---

.travis.yml
README.md
REQUIRE
src/Coluna.jl
src/nodealgs/algevalnode.jl

It's working now on both 0.7 and 1.0
By the same occasion we should all use julia 1.0 since now :)

Fixingtravis

---

REQUIRE
src/Coluna.jl
src/MOIWrapper.jl
src/problem.jl
test/moi_wrapper.jl
test/utils.jl

Tests are passing on my mac. We need to wait for GLPK to be tagged, update the REQUIRE, and this should be good to merge.

Updates for MOI 0.6

---

prototype_tests/juliaParallelizationTests/src/broadcastbenchmark.jl

Adding file with benchmark for the broadcast functionality

adding benchmark for broadcast

---

examples/CuttingStock_SubprobMultiplicity/run_csp.jl
examples/GeneralizedAssignment_SimpleColGen/run_sgap.jl

@IssamT 
Teobaldo spotted a problem in the examples. We were not `using GLPK`.

adding using GLPK to examples

---

src/decomposition.jl
src/formulation.jl
src/node.jl
src/solsandbounds.jl
src/solvers/colgen.jl

Fixing bugs related to the new maximisation feature

Maximization bug fixes

---

src/MOIwrapper.jl
src/problem.jl
src/reformulation.jl
test/models/gap.jl
test/runtests.jl

Resolves issue https://github.com/atoptima/Coluna.jl/issues/64

MOIWrapper - get obj value + get solution

---

src/algorithms/reformulationsolver.jl

Prepare formulation calling apply(::AbstractStrategy)

---

Manifest.toml
src/node.jl
src/variable.jl
test/preprocessing_tests.jl

Sp vars bound change

---

Manifest.toml
src/decomposition.jl
src/problem.jl

Get multiplicity of subproblems from BD

---

src/problem.jl

rm getparent annotations

---

Manifest.toml
Project.toml

Update project & manifest

---

src/Coluna.jl
src/algorithms/colgen.jl
src/containers/elements.jl
src/containers/members.jl
src/decomposition.jl
src/filters.jl
src/formulation.jl
src/manager.jl
test/unit/filters.jl

Uniformize filter functions

---

docs/src/start.md

Following BlockDecomposition release.

Update starting guide

---

src/optimizerwrappers.jl
test/full_instances_tests.jl

Error msg if no optimizer

---

src/optimizerwrappers.jl

Error msg for termination status not covered

---

src/Coluna.jl
src/containers/containers.jl
src/containers/nestedenum.jl

and creation of `Containers` submodule.

@nestedenum : smallest primes for greatest ancestors

---

README.md

Mv chat from gitter to discord

Update chat badge

---

src/MathProg/MOIinterface.jl
test/full_instances_tests.jl

@rrsadykov It should fix your bug in `algorithms`. My first version of tolerance fix was incorrect...

Fix round in fill primal result

---

docs/src/start.md
src/Coluna.jl
src/MOIwrapper.jl
src/MathProg/problem.jl
test/full_instances_tests.jl
test/preprocessing_tests.jl
test/pricing_callback_tests.jl
test/show_functions_tests.jl
test/unit/algorithms/masteripheur.jl

Optimizer builder of MOI 0.9.10 

---

src/Containers/nestedenum.jl

Print method for duties (nestedenum macro)

---

Manifest.toml
src/Algorithm/colgen.jl
src/Containers/Containers.jl
src/Containers/solsandbounds.jl
src/MathProg/decomposition.jl
src/MathProg/formulation.jl
src/MathProg/manager.jl
src/MathProg/projection.jl
src/parameters.jl

Fix #249 
& replace VarVarMatrix by a dynamic sparse matrix

Fix check if column exists

---

src/Coluna.jl
src/MathProg/MathProg.jl
src/MathProg/vcids.jl
src/globals.jl
src/parameters.jl
test/full_instances_tests.jl
test/pricing_callback_tests.jl
test/show_functions_tests.jl

Move parameters 

---

Manifest.toml
Project.toml
src/Coluna.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/MathProg/decomposition.jl
src/MathProg/formulation.jl
src/MathProg/optimizerwrappers.jl
src/MathProg/problem.jl
test/pricing_callback_tests.jl
test/runtests.jl

Fix #83 
Fix #206 : map is already there for variables (field `varmap` of `Optimizer`)

Pricing oracles

---

src/Algorithm/solveipform.jl
src/MathProg/decomposition.jl

Create artificial variables for equal constraints
Example from https://github.com/atoptima/Coluna.jl/issues/301 was infeasible with ColGen

Artificial vars for Equal constraints

---

src/Algorithm/Algorithm.jl
src/Algorithm/benders.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchinggroup.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/divide.jl
src/Algorithm/interface.jl
src/Algorithm/node.jl
src/Algorithm/solveipform.jl
src/Algorithm/solvelpform.jl
src/Algorithm/treesearch.jl
src/Algorithm/utilities/optimizationstate.jl
src/optimize.jl

This takes into account the new OptimizationState structure

Reorganisation of Algorithm submodule 

---

src/parameters.jl

It is already in SearchTreeAlgorithm
Fix #226

rm max_num_nodes & max_open_nodes in Params

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/colgen.jl
src/Algorithm/formstorages.jl
test/full_instances_tests.jl

@guimarqu This is the first version which seems to work. Can you check whether it is ok for you? 
To have a better version we need:
- to be able to quickly obtain the number of active master columns;
- to be able to retrieve LP basis.

Master columns cleanup

---

src/Algorithm/basic/cutcallback.jl
src/Algorithm/benders.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/MathProg/constraint.jl
src/MathProg/decomposition.jl
src/MathProg/formulation.jl
src/MathProg/types.jl
src/MathProg/varconstr.jl

ConstrKind : Core -> Essential

---

docs/src/dev/formulation.md
docs/src/user/callbacks.md
src/MathProg/duties.jl
src/MathProg/formulation.jl
src/MathProg/types.jl

Docstrings for formulation methods & mention of separation callbacks

More documentation

---

src/Coluna.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/MathProg/MathProg.jl
src/MathProg/constraint.jl
src/MathProg/formulation.jl
src/MathProg/problem.jl
src/MathProg/types.jl
src/MathProg/variable.jl
src/annotations.jl
src/decomposition.jl
src/optimize.jl
test/full_instances_tests.jl
test/preprocessing_tests.jl
test/show_functions_tests.jl
test/unit/MathProg/types.jl

- Implement automatic copy
- Move decomposition outside `MathProg`
- Move data structure that stores `Annotation`s outside `MathProg`
- Allow use of MOI direct mode

Rewrite MOI wrapper

---

.travis.yml
src/MathProg/MathProg.jl
src/MathProg/solutions.jl

- update travis file
- fix bug because of `contains`

Updates for julia 1.5

---

src/Algorithm/conquer.jl
src/MathProg/MathProg.jl

attempt to call an algo oustide Coluna

remove algo types in ColCutGenConquer

---

src/MathProg/problem.jl
test/full_instances_tests.jl

Initial bounds are Real

---

src/MOIwrapper.jl
test/full_instances_tests.jl

to be able to print the model in direct mode.

missing get for SolverName & NumberOfVariables MOI attr

---

Project.toml
src/optimize.jl

Patch release 0.3.2

---

src/Algorithm/treesearch.jl

Field `opt_state` does not exist in `Node`.

fix bug at the end of TreeSearch

---

src/optimize.jl
src/parameters.jl

Error when no solver provided

---

docs/src/dev/todo.md
src/Algorithm/benders.jl
src/Algorithm/treesearch.jl
src/MathProg/MathProg.jl
src/MathProg/problem.jl
src/MathProg/reformulation.jl
src/decomposition.jl
src/optimize.jl
test/issues_tests.jl
test/runtests.jl

fix #425 #223 
improvement for #301 
needed for #437

no reformulation when user does not provide decomposition

---

src/MOIwrapper.jl
src/MathProg/MathProg.jl
test/issues_tests.jl

fix MOI.empty!

---

src/MOIwrapper.jl
src/MathProg/MOIinterface.jl
src/MathProg/MathProg.jl
src/MathProg/buffer.jl
src/MathProg/formulation.jl
src/MathProg/manager.jl
src/MathProg/optimizerwrappers.jl
src/decomposition.jl
test/MathOptInterface/MOI_wrapper.jl
test/issues_tests.jl

- objective constant in now supported for Dantzig-Wolfe decomposition & original formulation
- fix last MIP edge cases of #436 
@rrsadykov I think the cost of the partial solutions can be handled in the objective now

Support constant in objective function

---

src/MOIwrapper.jl
test/optimizer_with_attributes_test.jl
test/runtests.jl

- #393 solved
- Added tests to the run_tests.jl file
- All tests passed

Allow optimizer with attributes

---

test/runtests.jl
test/subproblem_solvers_tests.jl

Issue #451 solved by [pull request #44](https://github.com/atoptima/BlockDecomposition.jl/pull/44) in BlockDecomposition.jl .

FIX: Subsolvers with Different Parameters. Issue #451

---

src/Algorithm/benders.jl
src/Algorithm/treesearch.jl
src/decomposition.jl
test/issues_tests.jl

Solver ColumnGeneration

---

src/Algorithm/colgenstabilization.jl
src/Algorithm/data.jl
src/Algorithm/formstorages.jl
src/Algorithm/interface.jl
src/Algorithm/node.jl
src/Algorithm/preprocessing.jl
src/Algorithm/storage.jl

rename StorageState -> RecordState

---

src/MOIwrapper.jl
test/issues_tests.jl
test/show_functions_tests.jl

Add method to get the number of constraints

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchingrule.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/colgenstabilization.jl
src/Algorithm/conquer.jl
src/Algorithm/data.jl
src/Algorithm/formstorages.jl
src/Algorithm/interface.jl
src/Algorithm/node.jl
src/Algorithm/preprocessing.jl
src/Algorithm/storage.jl
src/Algorithm/treesearch.jl
src/optimize.jl

task for #330 
- RecordState -> Record
- `restore_records!`, `restore_from_record!` and `restore_record!` -> `restore_from_record!`

Rename Record State -> Record

---

test/issues_tests.jl

The bug has been fixed in https://github.com/atoptima/BlockDecomposition.jl/pull/46
close #458 
tests will pass when BlockDecomposition 1.2.6 released.

Uncomment last test of `optimize_twice`

---

src/MathProg/MathProg.jl
src/MathProg/counters.jl
src/MathProg/formulation.jl
test/unit/counters.jl
test/unit/unit_tests.jl

Remove Counter

---

.github/workflows/ci.yml
Project.toml
src/ColunaBase/solsandbounds.jl
test/unit/containers/solsandbounds.jl

Work currently in progress.
To do:
close #480, close #479

Missing unit tests in Bounds and Solutions

---

src/MathProg/buffer.jl
src/MathProg/optimizerwrappers.jl
test/unit/MathProg/buffer.jl
test/unit/unit_tests.jl

Delete buffer changes when removing variable or constraint

---

docs/src/user/start.md

Add sum over j in J in the objective function of the problem formulation.

Fix problem formulation

---

src/Algorithm/branching/varbranching.jl
src/Algorithm/conquer.jl
src/Algorithm/interface.jl
src/Algorithm/storage.jl

StorageContainer -> Storage & fix arg order for restore_from_records

---

src/Algorithm/Algorithm.jl
src/Algorithm/colgenstabilization.jl
src/Algorithm/conquer.jl
src/Algorithm/data.jl
src/Algorithm/formstorages.jl
src/Algorithm/preprocessing.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/storage.jl
src/optimize.jl

Move storage & records in ColunaBase

---

docs/src/dev/todo.md
src/Algorithm/Algorithm.jl
src/Algorithm/basic/cutcallback.jl
src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/benders.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchinggroup.jl
src/Algorithm/branching/branchingrule.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/data.jl
src/Algorithm/divide.jl
src/Algorithm/interface.jl
src/Algorithm/preprocessing.jl
src/Algorithm/treesearch.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/storage.jl
src/MathProg/formulation.jl
src/MathProg/reformulation.jl
src/optimize.jl
test/user_algorithms_tests.jl

Task of #330 
- Storage dict are now stored in reformulation and formulations.
- Deletion of `AbstractData`
PR #509 must be reviewed and merged before this one.

Deletion of `AbstractData` 

---

.github/workflows/ci.yml
.github/workflows/documentation.yml
docs/Project.toml

Fix documentation deployment

---

src/Algorithm/Algorithm.jl
src/Algorithm/basic/cutcallback.jl
src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/benders.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/colgen.jl
src/Algorithm/colgenstabilization.jl
src/Algorithm/data.jl
src/Algorithm/formstorages.jl
src/Algorithm/interface.jl
src/Algorithm/preprocessing.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/storage.jl
src/MathProg/formulation.jl
src/MathProg/reformulation.jl
test/user_algorithms_tests.jl

Following our discussion to simplify how storages & records work.
- Wrap storage dict
- Bijection storage unit -> record
Task for #330

Bijection StorageUnit -> Record

---

.gitignore
src/MOIwrapper.jl
test/MathOptInterface/MOI_wrapper.jl

Add support of JuMP.write_to_file in direct mode

---

Project.toml
src/MOIwrapper.jl
src/MathProg/formulation.jl
src/MathProg/variable.jl
test/MathOptInterface/MOI_wrapper.jl

fix https://github.com/atoptima/Coluna.jl/issues/521#issuecomment-836709967

Add VarBranchingPriority

---

src/Algorithm/basic/solveipform.jl
src/Algorithm/utilities/optimizationstate.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/solsandbounds.jl
src/MOIwrapper.jl
src/MathProg/MOIinterface.jl
test/MathOptInterface/MOI_wrapper.jl
test/user_algorithms_tests.jl

MOI tests: intlinear

---

test/interfaces/model.jl

Remove negative costs

---

src/Algorithm/utilities/optimizationstate.jl
test/unit/optimizationstate.jl
test/unit/unit_tests.jl

Test in "test/unit/optimizationstate.jl" line 116 (`add_lp_dual_sol!`) was failing. For me it seemed that the sorting wasn't correct for dual solutions, that's why I reversed it.

Unit tests for OptimizationState

---

src/Coluna.jl
src/ColunaBase/solsandbounds.jl
test/unit/optimizationstate.jl

Add `Base.in(::Tuple{De,Va}, ::Solution{Mo,De,Va})` to allow `==` and `isequal` comparisons between solutions.

Solutions comparison operators

---

src/Algorithm/conquer.jl
src/Algorithm/utilities/optimizationstate.jl
src/MathProg/bounds.jl
src/MathProg/solutions.jl
test/unit/containers/solsandbounds.jl

Add isless(::Solution, ::Solution)

---

src/Coluna.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/solsandbounds.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/MathProg/constraint.jl
src/MathProg/formulation.jl
src/MathProg/manager.jl
src/MathProg/solutions.jl
src/MathProg/variable.jl
test/custom_var_cuts_tests.jl

task for #536
- Implement MOI set methods for custom data in Coluna
- Use `BlockDecomposition.AbstractCustomData`
- Add `custom_families_id` field to Env and pass the dict to FormulationManager

Follow up of "custom data": use BlockDecomposition methods `customvars!` and `customconstrs!`

---

.github/workflows/ci.yml
src/MOIwrapper.jl

Don't close fillmode in get terms of constraint

---

src/MOIwrapper.jl

https://github.com/atoptima/Coluna.jl/pull/564#discussion_r685066171

Fix retrieval of disaggregated solution

---

.github/workflows/documentation.yml

Fix ci yaml of documentation

---

src/MOIwrapper.jl
src/MathProg/MathProg.jl
src/MathProg/buffer.jl
src/MathProg/formulation.jl
src/MathProg/optimizerwrappers.jl
src/MathProg/varconstr.jl
test/MathOptInterface/MOI_wrapper.jl

update for #563 , closes #268, and closes #559

MOI linear10 passing

---

src/Algorithm/basic/cutcallback.jl
src/Algorithm/colgen.jl
src/Algorithm/treesearch.jl
src/Algorithm/utilities/optimizationstate.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/optimize.jl
test/issues_tests.jl

Give access to the dual solution of the master to the user

---

src/MathProg/MathProg.jl
src/MathProg/types.jl
test/unit/MathProg/formulations.jl

change `FormId` type to increase nb formulation limit

---

src/MOIwrapper.jl
src/MathProg/MOIinterface.jl
src/MathProg/buffer.jl
src/MathProg/formulation.jl
src/MathProg/varconstr.jl
test/MathOptInterface/MOI_wrapper.jl
test/runtests.jl
test/unit/MathProg/buffer.jl

~~fix of #620~~ -> 3 tests are not passing anymore.
fix 2 critical bugs:
- reset of the buffer
- deletion of an active variable or constraint

fix reset of buffer + deletion of active vars & constrs

---

src/MathProg/MOIinterface.jl
src/MathProg/buffer.jl
src/MathProg/formulation.jl
src/MathProg/optimizerwrappers.jl
test/e2e/generalized_assignment.jl
test/runtests.jl
test/unit/MathProg/buffer.jl

rm propagation of objective constant in subsolver

---

src/Algorithm/benders.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/single_var_branching.jl
src/Algorithm/data.jl
src/Algorithm/interface.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/Coluna.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/interface.jl
src/ColunaBase/storage.jl
src/MathProg/MathProg.jl
src/MathProg/formulation.jl
src/MathProg/reformulation.jl
src/MathProg/vcids.jl
src/decomposition.jl
test/integration/initial_columns_callback.jl
test/unit/Algorithm/colgen.jl

There is room for improvement. 
I think we should adapt the data structure `RecordsVector` to the arguments expected by `restore_from_record!` given that an algorithm may want to restore specific storage units from specific models (purpose of UnitUsage).

Start simplifying interface built on top of NewStorage/NewRecord

---

src/Algorithm/Algorithm.jl
src/Algorithm/branchcutprice.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/interface.jl
src/Algorithm/branching/printer.jl
src/Algorithm/branching/sbnode.jl
src/Algorithm/branching/single_var_branching.jl
src/Algorithm/treesearch.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/Algorithm/treesearch/interface.jl
test/runtests.jl
test/unit/Algorithm/treesearch_interface.jl

Expose Branching & Strong Branching API to customize the branching.
The next MRs will introduce a log printer for strong branching & documentation.

Branching API

---

src/Algorithm/Algorithm.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/interface.jl
src/Algorithm/branching/printer.jl
src/Algorithm/branching/sbnode.jl
src/Algorithm/branching/single_var_branching.jl

- split interface & implementation
- add printer

Branching printer

---

src/Algorithm/branchcutprice.jl
src/Algorithm/conquer.jl

Split ColCutGenConquer `run!` method

---

docs/src/api/storage.jl

Add methods to find best solution in storage docs

---

src/Algorithm/Algorithm.jl
src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/basic/subsolvers.jl
test/unit/Algorithm/subsolvers.jl

Reset subsolver parameters after optimization

---

src/Algorithm/basic/solvelpform.jl
src/Algorithm/basic/subsolvers.jl

MoiOptimize loglevel -> 2

---

Project.toml
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/conquer.jl
src/Algorithm/interface.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/Algorithm/treesearch/interface.jl
src/MathProg/MathProg.jl
src/MathProg/reformulation.jl
src/MathProg/types.jl
test/integration/improve_relax_callback.jl
test/runtests.jl

This branch introduces two independent features that are related to the same application of improving relaxations: a callback function to be executed before every cut generation and a mechanism to pass information from nodes to their descendants.

Improve relax callback

---

src/Algorithm/basic/cutcallback.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/sbnode.jl
src/Algorithm/colgen.jl
src/Algorithm/colgen/default.jl
src/Algorithm/colgen/printer.jl
src/Algorithm/colgen/utils.jl
src/Algorithm/conquer.jl
src/Algorithm/interface.jl
src/Algorithm/presolve/interface.jl
src/Algorithm/treesearch.jl
src/Algorithm/treesearch/printer.jl
src/Branching/rule.jl
src/ColGen/interface.jl
src/ColGen/pricing.jl
test/unit/ColGen/colgen_default.jl
test/unit/ColGen/colgen_iteration.jl

Column generation default printer

---

test/unit/Benders/benders_default.jl

actual outputs and expected outputs are indicated with comments above each test function

add benders tests

---

src/Algorithm/benders/default.jl
src/Algorithm/benders/printer.jl
src/Benders/Benders.jl
src/ColunaBase/solsandbounds.jl
src/decomposition.jl
test/unit/Benders/benders_default.jl
test/unit/MathProg/benders_decomposition.jl

Fix infeasibility detection in Benders

---

docs/src/api/branching.md
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/printer.jl
src/Algorithm/colgen.jl
src/Branching/Branching.jl

On correction in column generation algorithm + correction in strong branching printer

Correction for strong branching 

---

docs/src/start/advanced-demo.jl

Remarks:
- line 782: is the verb "convexify" a real word ? 
- both "subproblem" and "sub-problem" are used in the demo, it is the same for "preprocessing" and "pre-processing". To me both writings are correct but we may choose one of them and keep it for the entire file.

advanced-demo review

---

NEWS.md
src/Algorithm/benders/default.jl
src/Algorithm/colgen/default.jl
src/Algorithm/utilities/optimizationstate.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/interface.jl
src/ColunaBase/solsandbounds.jl
src/MathProg/types.jl

OptimizationState{F,S} -> OptimizationState{F}

---

test/unit/Benders/benders_default.jl
test/unit/Benders/benders_flow.jl
test/unit/Benders/benders_flow_extra.jl
test/unit/Benders/benders_iteration.jl
test/unit/Benders/extra_form.jl

I add some tests to be sure that case where Benders master is unbounded AND there are some integrality constraints is well-handled by the implementation.

Boost tests for Benders IP master

---

src/Algorithm/colgen/default.jl

ping @artalvpes 
To avoid counting the contribution of non-robust cuts twice when stabilization is unactive.

Fixing contribution of non-robust cuts in the case where stabilization is active

---

src/Algorithm/treesearch/branch_and_bound.jl
test/unit/TreeSearch/treesearch.jl

I added two more tests
- one to test the infeasible problem case
- one to test the infeasible subproblem case (subproblem in the sense "subspace of the BaB")
I also add checks about the treesearch output and some comments.

Fix run divide condition + boost tests treesearch

---

src/Algorithm/colgen/utils.jl
src/Algorithm/presolve/helpers.jl
src/Algorithm/presolve/interface.jl
test/unit/Presolve/build_formulation.jl

To perform presolve routines (rows deactivation, bounds tightening, cols fixing, and propagation), I need to use a specific representation of the formulations.

Presolve representation of DW reformulation

---

test/unit/Branching/criterion.jl

unit tests for branching criterion

---

src/Algorithm/formstorages.jl
src/Algorithm/presolve/interface.jl
src/MathProg/MOIinterface.jl
src/MathProg/MathProg.jl
src/MathProg/manager.jl
src/MathProg/varconstr.jl
src/MathProg/variable.jl
test/integration/MOI/fixed_variables.jl
test/unit/Algorithm/record_mastercolumns.jl
test/unit/Algorithm/record_staticvarconstr.jl
test/unit/MathProg/variables.jl
test/unit/Presolve/build_formulation.jl
test/unit/Presolve/propagation.jl

ping @rrsadykov 
related to #1061

Redefine partial solution

---

src/Algorithm/presolve/interface.jl
src/Tests/Parser/Parser.jl
test/unit/Presolve/build_formulation.jl

Presolve: consider variables that does not appear in coefficient matrix

---

src/MathProg/projection.jl
test/unit/MathProg/projection.jl

Correction in the column generation integrality check: continuous variables should be ignored

Correction in the column generation integrality check

---

src/decomposition.jl
test/unit/MathProg/dw_decomposition.jl

Correction in calculation of initial bounds of representative variables (in the case of negative bounds)

Correction for initial bounds of representative variables

---

.github/workflows/ci.yml
src/MathProg/vcids.jl

Also putting back the tests with the latest Julia version.
Closes #1124. 
Closes #1118.

Correction to support Julia 1.10 

---

src/MOIcallbacks.jl

Update to https://github.com/atoptima/BlockDecomposition.jl/pull/106

Use AnnotationCallback instead of Nothing
