src/algorithms/algorithm.jl
src/algorithms/reformulationsolver.jl
src/node.jl

First version status + automatic prepare! calling each algorithm

Status on node to handle formulation modifications/updates by the algorithms

---

Manifest.toml
src/algorithms/colgen.jl
src/algorithms/reformulationsolver.jl
src/incumbents.jl
src/node.jl
src/strategies/conquer/simplebnp.jl
test/full_instances_tests.jl
test/unit/incumbents.jl
test/unit/strategies/strategy.jl

ColumnGeneration phase one

---

src/clone.jl
src/decomposition.jl
src/formulation.jl

Make clone methods more flexibles

Clone with parameters

---

src/algorithms/colgen.jl
src/incumbents.jl
src/solsandbounds.jl
test/full_instances_tests.jl

Fix #146 
Make some methods of `AbstractSolution` more generic

Fix primal solution check

---

src/Coluna.jl
src/algorithms/reformulationsolver.jl
src/strategies/explore/simplestrategies.jl
src/strategies/strategy.jl

Strategies : treesearch -> explore

---

src/algorithms/masteripheur.jl

Skip rest mast ip heur if integer var unsupported

---

Manifest.toml
Project.toml
src/Coluna.jl
src/containers/nestedenum.jl
test/runtests.jl
test/unit/containers/nestedenum.jl
test/unit/unit_tests.jl

Structure to create a tree of duty using `UInt` instead of types. It'll allow us to have `VarData` and `ConstrData` bitstype.
Syntax to create a tree : 
```julia
Coluna.@nestedenum VarConstrDuty,
A ← VarConstrDuty,
A1 ← A,
A2 ← A,
A3 ← A,
B ← VarConstrDuty,
B1 ← B,
B2 ← B,
B3 ← B,
B3A ← B3,
B3B ← B3,
B3C ← B3,
```
Syntax to know if duty inherits from another : 
```julia
A1 ← A # Return true
A1 ← B # Return false
!(A1 ← B) # Return true
```
@vitornesello your opinion about the syntax ?

Nested enumeration container

---

src/Algorithm/benders.jl
src/Containers/Containers.jl
src/Containers/solsandbounds.jl
src/MathProg/MOIinterface.jl
src/MathProg/formulation.jl
src/MathProg/incumbents.jl
src/MathProg/optimizerwrappers.jl
src/MathProg/projection.jl
src/MathProg/vcids.jl
src/parameters.jl
test/full_instances_tests.jl
test/pricing_callback_tests.jl
test/runtests.jl
test/unit/containers/solsandbounds.jl
test/unit/incumbents.jl

- Replace the SortedDict by a PackedMemoryArray in the Solution container
- Fix a tolerance problem in `fill_primal_solution`.

Dynamic sparse vector for solutions

---

Manifest.toml
Project.toml
src/MathProg/projection.jl

fix #252 
Pure master variables was ignored...

Fix projection of dw reformulation to original formulation

---

src/Algorithm/colgen.jl
src/MathProg/decomposition.jl
src/MathProg/formulation.jl

Fix wrong duty for setupvar in master coeff matrix

---

src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/solveipform.jl
src/Algorithm/solvelpform.jl

@rrsadykov  I think you are right, it's better to use a log_level attribute in algorithms instead of `@logmsg`. However, we should keep the same rules that `@logmsg` :  `1`silent mode, `0` default value, the lower the value (-1, -2, -3...), the more you print.

log_level instead logmsg in SolveIpForm

---

src/MathProg/projection.jl

For #323 
In the master solution, subproblem representative variables had subproblem duties instead of master duties.

Representatives of master sol should have master duty

---

src/Algorithm/solveipform.jl
src/Algorithm/solvelpform.jl
src/MathProg/MOIinterface.jl
src/MathProg/optimizerwrappers.jl
test/full_instances_tests.jl

use silent attribute to mute subsolvers instead of redirecting the output.
needed in #333

silent mode for subsolvers

---

src/MathProg/clone.jl
src/MathProg/constraint.jl
src/MathProg/decomposition.jl
src/MathProg/formulation.jl
src/MathProg/new_varconstr.jl

- keywork argument for `setconstr!` to create the local artificial variables with the constraint
- (de)activate a constraint and its artificial variables at the same time

Create local artifical variables in setconstr!

---

docs/make.jl
docs/src/dev/algorithms.md
src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/solveipform.jl
src/Algorithm/solvelpform.jl
src/Algorithm/treesearch.jl

Start documentation for algorithms

---

src/Algorithm/colgen.jl
src/Coluna.jl
src/MathProg/optimizerwrappers.jl
src/globals.jl

This implementation needs Gurobi to work.

Multi-threading on solving subproblems

---

src/Algorithm/treesearch.jl

Address https://github.com/atoptima/Coluna.jl/pull/351#issuecomment-633612306

Print node in branching tree after conquer

---

src/Algorithm/colgen.jl
test/full_instances_tests.jl

Detect subproblem infeasibility

---

docs/make.jl
docs/src/dev/reformulation.md
src/Algorithm/preprocessing.jl
src/MathProg/MathProg.jl
src/MathProg/decomposition.jl
src/MathProg/reformulation.jl

getters & doc for Reformulation

---

src/Algorithm/Algorithm.jl
src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/benders.jl
src/Algorithm/colgen.jl
src/Algorithm/colgenstabilization.jl
src/Algorithm/conquer.jl
src/Algorithm/node.jl
src/Algorithm/treesearch.jl
src/Algorithm/utilities/optimizationstate.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/nestedenum.jl
src/ColunaBase/solsandbounds.jl
src/MOIcallbacks.jl
src/MOIwrapper.jl
src/MathProg/MOIinterface.jl
src/MathProg/MathProg.jl
src/MathProg/optimizerwrappers.jl
src/MathProg/projection.jl
src/MathProg/solutions.jl
src/optimize.jl
test/unit/containers/solsandbounds.jl

I kept `NODE_LIMIT` because it can be usefull when we call subsolvers through MOI, or when we only solve the root node.
I replaced `NOT_YET_DETERMINED`  by  `UNKOWN_TERMINATION` (symmetric to `UNKNOWN_FEASIBILITY`) & `UNDEFINED`.

Improve termination statuses

---

src/Algorithm/utilities/optimizationstate.jl

It's better when we can read the code.

expand & rm macro for update solutions methods of OptimizationState

---

src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/colgen.jl
src/Coluna.jl
src/ColunaBase/solsandbounds.jl
src/MathProg/MathProg.jl
src/MathProg/solutions.jl

- it's not possible to create "empty solution" anymore, it's better to use `nothing` if there is no solution.
- use of only one `OptimizationState` in `SolveIpForm` & `SolveLpForm` instead of two.
- take into account param `get_dual_solutions` in `SolveLpForm`
- `concatenate_sols` becomes `cat` and supports both primal & dual solutions

SolveIpForm & SolveLpForm refactoring

---

src/Algorithm/conquer.jl
src/Algorithm/treesearch.jl
src/MOIwrapper.jl
src/MathProg/bounds.jl
test/full_instances_tests.jl

Fix #417 
- gap limit of `TreeSearchAlgorithm`
- fix comparisons of bounds : replace `isapprox = |lb - ub| / max(lb, ub) < rtol` by `_gap_closed = |lb - ub| / min(lb, ub) < rtol`
- `MOI.RelativeGap` now available

gap limit + improve comparison of bounds + MOI.RelativeGap

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/treesearch.jl

See the attached file as an example of the generated branching tree.
[cvrp2.pdf](https://github.com/atoptima/Coluna.jl/files/5824580/cvrp2.pdf)

Fixing the branching tree file

---

Project.toml
src/Algorithm/basic/cutcallback.jl
src/Algorithm/basic/solveipform.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/benders.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchinggroup.jl
src/Algorithm/branching/branchingrule.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/divide.jl
src/Algorithm/interface.jl
src/Algorithm/preprocessing.jl
src/Algorithm/treesearch.jl
src/Coluna.jl
src/MOIcallbacks.jl
src/MathProg/MOIinterface.jl
src/MathProg/MathProg.jl
src/MathProg/clone.jl
src/MathProg/formulation.jl
src/MathProg/vcids.jl
src/decomposition.jl
src/globals.jl
src/optimize.jl
src/parameters.jl
test/user_algorithms_tests.jl

- mandatory argument for the algorithms 
- remove all global mutable variables (!)
In the future, `Env` will allows us to simplify algorithm architecture by moving storage in it

Introducing Env

---

src/Algorithm/basic/cutcallback.jl
src/Algorithm/basic/solvelpform.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/storage.jl
src/Algorithm/treesearch.jl
src/Coluna.jl
src/MOIcallbacks.jl
src/MathProg/duties.jl

Note: I have added several (disabled) debugging tools used to find the bug.

Fixed a bug when restoring master cuts in strong branching

---

docs/src/dev/formulation.md
docs/src/dev/todo.md
src/Coluna.jl
src/MOIwrapper.jl
src/MathProg/MathProg.jl
src/MathProg/formulation.jl
src/MathProg/problem.jl
src/decomposition.jl
src/optimize.jl
test/unit/MathProg/variables.jl
test/unit/constraint.jl
test/unit/variable.jl

Update Formulation docstring

---

src/Algorithm/interface.jl
src/ColunaBase/ColunaBase.jl
src/ColunaBase/storage.jl

I removed getters of `Storage` (except `getunit` for the moment) because methods were only used in `storages.jl` and so seem to be private.
task for #330

Renaming in storage

---

src/Algorithm/branching/branchinggroup.jl

fix strong branching score calculation

---

docs/src/dev/formulation.md
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchingrule.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/treesearch.jl
src/MOIwrapper.jl
src/MathProg/MathProg.jl
src/MathProg/clone.jl
src/MathProg/formulation.jl
src/MathProg/varconstr.jl
src/MathProg/variable.jl
test/full_instances_tests.jl

This functionality works, but we also need to change the type of branching priorities in `BlockDecomposition` from `Int` to `Float`.  
The idea of fractional branching priorities to have both "soft" and "hard" branching priorities in strong branching:
- If the number of branching candidates with priority 4.0 is less than the maximum number, no branching candidates with priority 3.0 will be considered. 
- If the number of branching candidates with priority 3.5 is less than the maximum number, then some branching candidates with priority 3.0 will be considered (to bring the total number to the maximum). 
- If the number of branching candidates with priority 3.5 is not less than the maximum number, then no branching candidates with priority 3.0 will be considered.

Support of variable branching priorities in the branching algorithm

---

src/MOIcallbacks.jl
src/MathProg/duties.jl
src/MathProg/formulation.jl
src/MathProg/problem.jl
src/decomposition.jl
test/interfaces/model.jl
test/unit/MathProg/buffer.jl
test/unit/MathProg/variables.jl
test/unit/constraint.jl
test/unit/variable.jl

Custom information about Dantzig-Wolfe subproblems

---

src/Algorithm/Algorithm.jl
src/Algorithm/conquer.jl
test/user_algorithms_tests.jl

docstring for restricted master heuristic

---

.github/workflows/ci.yml
src/Algorithm/Algorithm.jl
src/Algorithm/benders.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchinggroup.jl
src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/treesearch.jl
src/Algorithm/utilities/optimizationstate.jl
src/ColunaBase/solsandbounds.jl
src/MOIwrapper.jl
src/MathProg/MathProg.jl
src/MathProg/bounds.jl
test/MathOptInterface/MOI_wrapper.jl
test/full_instances_tests.jl
test/runtests.jl
test/unit/MathProg/bounds.jl
test/unit/containers/solsandbounds.jl
test/unit/unit_tests.jl
test/user_algorithms_tests.jl

- `ObjValues` is used only in `OptimizationState`, so I moved all the docstring in `OptimizationState` methods.
- tests & doc for PrimalBound, DualBound and ObjValues
- remove some duplicated methods
- I fixed a bug I introduced in #543 
- Fix CI

Refactoring `ObjValues` & `OptimizationState`

---

src/decomposition.jl
test/issues_tests.jl

fix #553
At the moment, Coluna does not detect anonymous variables when `direct_mode = false` but the annotation of an anony var is nothing (cf https://github.com/atoptima/BlockDecomposition.jl/pull/65/commits/d86fa7e01a89de678433ac6af5dfc32113135b1a)

rm support of anonymous variables & constraints

---

src/MOIwrapper.jl
test/MathOptInterface/MOI_wrapper.jl

fix #563 
I hoped to find a method like this in MOI:
```julia
function MOI.set(
model::MOI.ModelLike,
attr::MOI.AbstractConstraintAttribute,
bridge::SplitIntervalBridge,
value,
)
MOI.set(model, attr, bridge.lower, value)
MOI.set(model, attr, bridge.upper, value)
end
```
But I couldn't find any. The fallback we get (https://github.com/jump-dev/MathOptInterface.jl/blob/978096044b3ab89ae57e778c9369f2198dba49af/src/Bridges/bridge.jl#L120) seems to confirm it is necessary to add a new set method at least for `SplitIntervalBridge`.

Add support for `AffExpr, MathOptInterface.Interval{Float64}`

---

src/optimize.jl

These warnings are misleading (cf https://github.com/atoptima/Coluna.jl/issues/545#issuecomment-860415524)

Rm warnings if cost of artificial vars not provided by the user

---

src/Algorithm/treesearch.jl
test/full_instances_tests.jl

dual bound of tree search is dual bound of open nodes

---

src/Algorithm/branching/branchingalgo.jl

Correction of a bug in strong branching

---

src/Algorithm/Algorithm.jl
src/Algorithm/branchcutprice.jl
src/Algorithm/branching/varbranching.jl
test/bound_callback_tests.jl
test/full_instances_tests.jl
test/optimizer_with_attributes_test.jl
test/pricing_callback_tests.jl
test/subproblem_solvers_tests.jl

Introduces `Coluna.Algorithm.BranchCutAndPriceAlgorithm` alias for a simplified parameterisation of the branch-cut-and-price algorithm.
Addresses issue #478.

Alias for a simplified BCP parameterisation 

---

src/MathProg/vcids.jl
test/runtests.jl
test/unit/MathProg/vcids.jl
test/unit/unit_tests.jl

This is a critical bug. A patch release will follow.

create_hash always returns int

---

src/Algorithm/colgen.jl
src/MathProg/MathProg.jl
src/MathProg/formulation.jl
test/unit/Algorithm/colgen.jl

ping @librallu @artalvpes (this fix will be merged in `release_v0.4.0`)

Support insertion of identical columns at same colgen iteration

---

src/Algorithm/branching/branchinggroup.jl
src/Algorithm/branching/varbranching.jl
src/Algorithm/conquer.jl
src/Algorithm/divide.jl
src/Algorithm/node.jl
src/Algorithm/treesearch.jl
test/runtests.jl

I created a new type of nodes `SbNode` which is basically a copy of the `Node` type to decouple the strong branching algorithm from the current tree search implementation.
I consider that the evaluation of branching candidates should not depend on the tree search implementation.

Decoupling strong branching from tree search data structures

---

src/Algorithm/Algorithm.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/branchinggroup.jl
src/Algorithm/branching/branchingrule.jl
src/Algorithm/branching/candidates.jl
src/Algorithm/branching/interface.jl
src/Algorithm/branching/selectioncriteria.jl
test/runtests.jl

The branching candidate now contains information that were previously in the branching group.

Removing branching group

---

docs/make.jl
docs/src/api/branching.md
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/interface.jl

Documentation of the branching API.
We may need to isolate APIs in different submodules because a few functions may have the same name in different APIs. It's confusing.

Branching API documentation

---

src/MathProg/MathProg.jl
src/MathProg/formulation.jl
src/MathProg/vcids.jl
test/unit/MathProg/vcids.jl

So we can use them as indices of Julia sparse arrays.

`Id` subtype of `Integer`

---

src/MathProg/MathProg.jl
src/MathProg/formulation.jl
src/MathProg/manager.jl
src/MathProg/varconstr.jl
src/MathProg/variable.jl
test/unit/MathProg/variables.jl

Now, you can fix an active and explicit variable in a formulation.
Fixing a variable means it has the same lower and upper bound and it is then deactivated until one of its bounds changes.

Fix variable of formulation

---

src/Algorithm/colgen.jl
test/unit/Algorithm/colgen.jl

Fixes a bug in the double addition (in the same iteration) of a column that was deactivated in the master. Still need a specific unit test for that.

Fix the double addition of deactivated columns

---

src/Algorithm/colgen.jl
src/Algorithm/conquer.jl
src/Algorithm/treesearch.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/Algorithm/utilities/helpers.jl
src/env.jl

Better implementation of the time limit

---

src/Algorithm/colgen.jl
src/Algorithm/utilities/helpers.jl
src/MathProg/formulation.jl
test/unit/Algorithm/colgen.jl

fix bug in colgen when subproblem is infeasible or unbounded

---

test/integration/initial_columns_callback.jl
test/integration/parser.jl
test/parser.jl
test/unit/Algorithm/colgen.jl

This PR will:
- Refactor some parts of the parser to add more options when writing the subproblems in the formulation
- Substitute some reformulations (built by hand) by calling the parser with the reformulation written as a string

Refactor reformulation parser

---

src/Algorithm/colgen/printer.jl
src/ColGen/interface.jl
test/e2e_extra/gap/gap.jl
test/unit/ColGen/colgen_printer.jl

fix gap test with lazy cuty sep

---

src/Algorithm/basic/cutcallback.jl
src/Algorithm/benders/default.jl
src/Algorithm/branchcutprice.jl
src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/interface.jl
src/Branching/Branching.jl
test/e2e/gap/generalized_assignment.jl

fix incremental compilation may be fatally broken

---

src/ColGen/interface.jl

add isnothing(stage) on colgen stopping condition

---

src/Algorithm/colgen/default.jl
src/ColGen/interface.jl
test/unit/ColGen/colgen_phase.jl

I changed the ColGenPhaseOutput structure to add a field `min_sense` (boolean). I use it to enforce the convergence condition in `colgen_has_converged` (I add the condition `( (output.min_sense) && (output.db >= output.mlp) ) || ( !(output.min_sense) && (output.db <= output.mlp) )` to the condition `abs(output.mlp - output.db) < 1e-5`
Remark: if I change the old condition `abs(output.mlp - output.db) < 1e-5` by new condition `( (output.min_sense) && (output.db >= output.mlp) ) || ( !(output.min_sense) && (output.db <= output.mlp) ),` test `gap_with_all_phases_in_colgen` failed (see log) 
[message.txt](https://github.com/atoptima/Coluna.jl/files/11396121/message.txt)

enforce convergence condition

---

src/Algorithm/basic/solveipform.jl
src/Algorithm/branching/scores.jl
src/Algorithm/colgenstabilization.jl
src/Algorithm/utilities/optimizationstate.jl
src/ColunaBase/solsandbounds.jl
src/MathProg/bounds.jl
src/MathProg/problem.jl
test/unit/ColunaBase/solsandbounds.jl
test/unit/MathProg/bounds.jl

Bound{Space, Sense} -> Bound

---

src/MathProg/MOIinterface.jl
src/MathProg/MathProg.jl
src/MathProg/manager.jl
src/MathProg/types.jl
src/MathProg/variable.jl
test/unit/MathProg/variables.jl

close #799 
It also removes the need for the variable basis status to get the dual multipliers of variable bound constraints.

`Interval` -> `GreaterThan` & `LowerThan`

---

src/Algorithm/benders/default.jl
test/unit/Benders/benders_cuts.jl
test/unit/Benders/benders_default.jl
test/unit/Benders/benders_iteration.jl

In file ```benders_cuts.jl``` I create a formulation and I test with fixed (dumb) dual solutions that the cuts coefficients are well computed (in the case of a feasibility and an optimality cut). For the right-hand side, I test several cases ; when a variable has a upper/lower bound and also when there is an equality (but we have to check that last case, see issue  #934)

Test benders cuts

---

test/unit/Benders/benders_flow.jl
test/unit/Benders/benders_flow_extra.jl

Two tests in ```benders_flow.jl```
- benders_flow_unbounded_master ; I check that we enter ```treat_unbounded_master_problem_case!``` method, the test passed
- benders_flow_infeasible_sp ; I create a formulation with some 1st level variables fixed so that the sp is infeasible. I was expected to enter ```treat_infeasible_separation_problem_case!``` but this is not the case. But maybe it is not the expected behaviour given my formulation ?

Test Benders flow for infeasible/unbounded

---

docs/make.jl
docs/src/man/blockdecomposition.md
docs/src/man/decomposition.md

This is an attempt to re-organise the section ```man/decomposition``` of the documentation. The files are now organized as follow:
```
Decomposition
|_ Decomposition paradigms
|_ Dantzig-Wolfe
|_ Benders
|_ Setup decomposition using BlockDecomposition
```
I also add some backup about Benders. There are some TODOs left ; we should decide if some information has to go explicitly in the doc or if we have to give some links.

re-organize and boost man/decomposition

---

src/Algorithm/conquer.jl

It was not defined as an AbstractAlgorithm. Why didn't the tests get this bug?

Fix the definition of the NodeFinalizer algorithm

---

src/Algorithm/treesearch/branch_and_bound.jl

This is important for the reduced cost fixing and enumeration to work in the ColunaVrpSolver application.

Make the initial IP primal bound reach the conquer input

---

src/Algorithm/branching/interface.jl
src/Algorithm/treesearch.jl

children in ```treesearch.jl```is now responsible to decide if the divide should be run or not, depending on the divide input (obtained from the conquer output).  The checks have been moved from the run! method of divide.

create a routine in children to check if the divide should be run

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/conquer.jl
src/Algorithm/treesearch.jl
src/Algorithm/treesearch/branch_and_bound.jl

I created a routine run_conquer in ```treesearch.jl```responsible to perform checks before eventually calling the run! of conquer. This allowed to remove the boolean run_conquer from the conquer input.

Checks before conquer

---

src/MathProg/bounds.jl

We create a subroutine `gap_closed` that takes as two bounds as arguments  instead of an optimization state (as in `_ip_gap_closed`). ```_ip_gap_closed``` calls this subroutine now.

create subroutine gap_closed in bounds.jl

---

test/revise.jl
test/unit/TreeSearch/treesearch.jl
test/unit/run.jl

For the moment I only test the execution flow i.e. if we enter or not enter run! of conquer and divide at each node. 
I spot at least one bug ; when the node is pruned after conquer it looks like we still enter divide.
TODO: add tests about the output of the tree search

integrate first tests

---

test/unit/TreeSearch/treesearch.jl

I added two more tests for tree search
- one with the search tree all explored and no primal solution found
- one with the search tree all explored and a primal solution found
both pass

add tests for tree search

---

src/Algorithm/conquer.jl
src/Algorithm/treesearch/branch_and_bound.jl
test/e2e_extra/advanced_colgen/node_finalizer_tests.jl

Note that the test was changed to expect "optimal" as the solution status. For that, the node finalizer needed to set also the LP dual bound in the exact mode. This makes more sense as the node should be considered as conquered in the exact mode.

Fix the primal and dual bounds set by the node finalizer

---

src/Algorithm/branching/branchingalgo.jl

Consider also removing `ip_primal_sols_found` from everywhere and using `Branching.get_global_primal_handler(input)` instead.

For the IP primal solutions from branching candidate evaluations not to be lost

---

Project.toml
src/MathProg/reformulation.jl
src/decomposition.jl
test/parser.jl
test/unit/Algorithm/check_parameters.jl
test/unit/Benders/benders_cuts.jl
test/unit/Benders/benders_default.jl
test/unit/Branching/branching_default.jl
test/unit/MathProg/benders_decomposition.jl
test/unit/MathProg/projection.jl
test/unit/TreeSearch/treesearch.jl

Tests depend a lot on hard-coded formulation ids. It makes maintenance difficult.

Build Reformulation after Formulations

---

docs/src/api/branching.md
src/Algorithm/branching/printer.jl
src/Algorithm/branching/scores.jl
src/Algorithm/branching/single_var_branching.jl
src/Branching/Branching.jl
src/Branching/candidate.jl

Generating child nodes from branching candidates is moved from `select!()` to `advanced_select!()`. This allows us to simplify the interface of branching candidates (we remove nodes from them). This simplification also serves to prepare the diving implementation.

Remove children nodes from branching candidates

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/printer.jl
src/Algorithm/branching/sbnode.jl
src/Algorithm/branching/scores.jl
src/Algorithm/branching/single_var_branching.jl
src/Algorithm/treesearch.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/TreeSearch/TreeSearch.jl
test/unit/Branching/branching_default.jl
test/unit/TreeSearch/treesearch.jl

This pull request is a way to ensure that the conquer is not run again needlessly 1) after strong branching 2) at the root of the diving. After running the conquer algorithm, its output (`OptimizationState`) is put to the node so that the divide algorithm can use it even if it is not run immediately after. 
In the future, we would need to define two conquer algorithms for the branch-and-bound (one for the root and one for other nodes), as for the moment we always rely on strong branching to do complete evaluation of the candidate branches. Sometimes, we may want to do a "partial" evaluation in the strong branching. Then, we would need to define an empty conquer algorithm which does nothing and returns nothing. In the when it is used, we would rely on the node to already  possess a conquer …

Run conquer algorithm in TreeSearch only if `conquer_output` of the node is empty

---

src/MathProg/duties.jl
src/MathProg/formulation.jl
src/MathProg/reformulation.jl
test/unit/MathProg/dw_decomposition.jl

Possibility to print the whole reformulation with only user-defined variables and constraints

Nice reformulation output

---

src/Algorithm/treesearch.jl
src/Algorithm/treesearch/branch_and_bound.jl
src/Algorithm/treesearch/printer.jl
src/TreeSearch/TreeSearch.jl
src/TreeSearch/explore.jl
test/unit/Algorithm/explore.jl
test/unit/TreeSearch/treesearch.jl

• Correction for output of the global dual bound: for that we moved its calculation from `TreeSearch.children` function to `TreeSearch.stop` function
• At the same time, we simplified the `TreeSearch` interface.
Closes #1077.

Correction for output of the global dual bound

---

src/Algorithm/branching/branchingalgo.jl
src/Algorithm/branching/printer.jl
src/Algorithm/colgen/printer.jl
src/Algorithm/conquer.jl
src/Algorithm/heuristic/restricted_master.jl
src/ColGen/ColGen.jl

• Restored strong branching output
• Correction for global bounds output when strong branching is used 
• Output information every time an improving primal solution is found
Closes #1119

Restore correct strong branching output

---

docs/src/man/presolve.md
src/Algorithm/presolve/interface.jl
src/Algorithm/presolve/propagation.jl
test/unit/Presolve/presolve.jl

Fixed bug in the presolve algorithm when the partial solution to fix contains deactivated variables

Fixed bug in presolve

---

docs/src/api/colgen.md

Mermaid interprets `o-->` as an arrow starting with a dot, see https://mermaid.js.org/syntax/flowchart.html#multi-directional-arrows. Weirdly enough, it actually does not actually show this dot but it consumes the `o` and we are left with only `n` in the label. Adding this space makes sure that the label is `no`.

Fix label in mermaid diagram

---

docs/src/start/pricing.jl

Fixes the following errors I got when running the example:
```
ERROR: LoadError: MethodError: no method matching submit(::Model, ::BlockDecomposition.PricingSolution{…}, ::Float64, ::Vector{Any}, ::Vector{…})
```
and
```
ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
```

Fix pricing tutorial when no job is assigned
